# Generated by Django 5.2 on 2025-04-10 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_userartistselection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='release_date',
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('tracks', models.ManyToManyField(related_name='playlists', to='web.track')),
            ],
        ),
        migrations.DeleteModel(
            name='UserArtistSelection',
        ),
    ]
