# Generated by Django 5.2 on 2025-05-09 13:00

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_remove_track_duration_ms_remove_track_popularity_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='playlist',
            unique_together={('title', 'user')},
        ),
    ]
